name: Build and Push to GitHub Container Registry

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: ./.devcontainer
          tags: |
            ghcr.io/${{ github.actor }}/creusot-devcontainer:git-${{ github.sha }}
            ghcr.io/${{ github.actor }}/creusot-devcontainer:latest
